# Generated by Django 4.1 on 2022-08-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('auctio_status', models.BooleanField()),
                ('time_create', models.DateTimeField()),
                ('start_bid', models.FloatField()),
                ('category_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='auctions.category')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
