# Generated by Django 4.1 on 2022-08-22 16:24

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('comment_time', models.DateTimeField()),
                ('items', models.ForeignKey(on_delete=builtins.callable, related_name='items', to='auctions.auction_list')),
                ('user_comment', models.ForeignKey(on_delete=builtins.callable, related_name='time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
