# Generated by Django 4.1 on 2022-08-22 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_list_id_alter_bids_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='category_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='auctions.category'),
        ),
    ]
